spring:
  application:
    name: rating-service

  datasource:
    url: jdbc:postgresql://localhost:5432/rating_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
